name: network
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  dio: ^4.0.4
  logger: ^1.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
